---
- name: Add Mozilla repo with signing key
  ansible.builtin.deb822_repository:
    name: mozilla
    types: [deb]
    uris: "https://packages.mozilla.org/apt"
    suites: [mozilla]
    components: [main]
    signed_by: https://packages.mozilla.org/apt/repo-signing-key.gpg
    state: present
    enabled: yes

- name: Add apt pin
  copy: src=./roles/mozilla/files/mozilla dest=/etc/apt/preferences.d/mozilla

- name: Install Firefox
  ansible.builtin.apt:
    name:
      - firefox
      - firefox-devedition
    state: present
    update_cache: true

- name: Install Thunderbird
  ansible.builtin.apt:
    name: thunderbird
    state: present
