---
- name: Add 1Passwrd repo with signing key
  ansible.builtin.deb822_repository:
    name: onepassword
    types: [deb]
    uris: "https://downloads.1password.com/linux/debian/amd64"
    suites: [stable]
    components: [main]
    signed_by: https://downloads.1password.com/linux/keys/1password.asc
    state: present
    enabled: yes

- name: Install 1Password and 1Password CLI
  ansible.builtin.apt:
    name:
      - 1password
      - 1password-cli
    state: present
    update_cache: true
