---
- name: Download 1Password DEB
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
    dest: /tmp/1password-latest.deb
    mode: 0440

- name: Install 1Password
  ansible.builtin.apt:
    deb: /tmp/1password-latest.deb
    state: present

- name: Download 1Password CLI DEB
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/debian/amd64/stable/1password-cli-amd64-latest.deb
    dest: /tmp/1password-cli-amd64-latest.deb
    mode: 0440

- name: Install 1Password CLI
  ansible.builtin.apt:
    deb: /tmp/1password-cli-amd64-latest.deb
    state: present
