---
- name: Add Fish repo with signing key
  ansible.builtin.deb822_repository:
    name: fish
    types: [deb]
    uris: "http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_12"
    suites: [/]
    signed_by: https://download.opensuse.org/repositories/shells:fish:release:3/Debian_12/Release.key
    state: present
    enabled: yes

- name: Install Fish
  ansible.builtin.apt:
    name: fish
    state: present
    update_cache: true

- name: Change shell to Fish
  ansible.builtin.user:
    name: dean
    shell: /usr/bin/fish

- name: Check if .rbenv exists
  stat:
    path: "~/.rbenv"
  register: rbenv
  become: no

- name: Create functions directory
  file:
    state: directory
    path: '~/.config/fish/functions'
  become: no

- name: Copy fish config
  copy: src=./roles/fish/files/config.fish dest=~/.config/fish/config.fish
  become: no
