---
- name: Add Fish apt repo (Ubuntu)
  ansible.builtin.apt_repository:
    repo: "ppa:fish-shell/release-3"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Download Fish apt key (Debian)
  ansible.builtin.get_url:
    url: https://download.opensuse.org/repositories/shells:fish:release:3/Debian_12/Release.key
    dest: /etc/apt/trusted.gpg.d/fish.asc
  when: ansible_distribution == "Debian"

- name: Add Fish repository (Debian)
  ansible.builtin.apt_repository:
    repo: "deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_12/ /"
    filename: fish
    state: present
  when: ansible_distribution == "Debian"

- name: Install Fish
  ansible.builtin.apt:
    name: fish
    state: present
    update_cache: true

- name: Change shell to Fish
  ansible.builtin.user:
    name: dean
    shell: /usr/bin/fish

- name: Check if .rbenv exists
  stat:
    path: "~/.rbenv"
  register: rbenv
  become: no

- name: Create functions directory
  file:
    state: directory
    path: '~/.config/fish/functions'
  become: no

- name: Copy fish config
  copy: src=./roles/fish/files/config.fish dest=~/.config/fish/config.fish
  become: no
