---
- name: Install pre-requisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - dirmngr
    state: present

- name: Download Buildkite Agent apt key
  ansible.builtin.get_url:
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/32A37959C2FA5C3C99EFBC32A79206696452D198
    dest: /etc/apt/keyrings/buildkite-agent.asc
    mode: '0644'
    force: true

- name: Add Buildkite Agent repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/buildkite-agent.asc] https://apt.buildkite.com/buildkite-agent stable main"
    filename: buildkite-agent
    state: present

- name: Install Buildkite Agent
  ansible.builtin.apt:
    name: buildkite-agent
    state: present
    update_cache: true
