---
- hosts: dev-desktop
  become: yes

  vars:
    docker_install_compose_plugin: true
    docker_install_compose: false
    docker_users:
      - "dean"
    rbenv_versions:
      - 3.2.2
      - 3.1.2
    rbenv_default_ruby: 3.2.2
    tailscale_up_skip: true

  roles:
    - update
    - common
    - geerlingguy.docker
    - artis3n.tailscale
    - users-dean

    - dotfiles
    - rbenv
    - fish
    - flatpak
    - 1password
  
  tasks:
    - name: Install database libraries
      ansible.builtin.apt:
        name:
          - sqlite3
          - libsqlite3-dev
          - default-mysql-client
          - default-libmysqlclient-dev
          - libpq-dev
        state: present
    - name: Install additional tools
      ansible.builtin.apt:
        name:
          - ffmpeg
          - libvips42
        state: present
