---
- hosts: dev
  become: yes

  vars:
    docker_install_compose_plugin: true
    docker_install_compose: false
    docker_users:
      - "dean"

  roles:
    - update
    - common
    - mozilla
    - geerlingguy.docker
    - fish
    - { name: atuin, become: no }
    - { name: dotfiles, become: no }
    - { name: mise, become: no }
    - tailscale
    - aws
    - github-cli
    - flatpak
    - onepassword
    - vscode
    - sublime
    - kopia

  tasks:
    - name: Install database libraries
      ansible.builtin.apt:
        name:
          - sqlite3
          - libsqlite3-dev
          - default-mysql-client
          - default-libmysqlclient-dev
          - libpq-dev
        state: present

    - name: Install additional tools
      ansible.builtin.apt:
        name:
          - ffmpeg
          - libvips42
          - vlc
          - libavcodec-extra
          - yakuake
        state: present
