---
- hosts: dev
  become: yes

  roles:
    # - dotfiles
    # - ssh-key
    # - rbenv
    - artis3n.tailscale
    # - {name: fish, become: yes}
  
  vars:
    rbenv_versions:
      - 3.2.2
    rbenv_default_ruby: 3.2.2
    tailscale_up_skip: true
  
  # tasks:
  #   - name: Install database libraries
  #     ansible.builtin.apt:
  #       name:
  #         - sqlite3
  #         - libsqlite3-dev
  #         - default-mysql-client
  #         - default-libmysqlclient-dev
  #         - libpq-dev
  #       state: present
  #   - name: Install additional tools
  #     ansible.builtin.apt:
  #       name:
  #         - ffmpeg
  #         - libvips42
  #       state: present

  #   - name: Install fish
  #     ansible.builtin.apt:
  #       name: fish
  #       state: present
  #     become: yes

  #   - name: Change shell to fish
  #     ansible.builtin.user:
  #       name: dean
  #       shell: /usr/bin/fish
  #     become: yes


  # tasks:
  #   - import_tasks: tasks/docker.yml
  #   - import_tasks: tasks/apps.yml
