---
- hosts: dev
  become: yes

  vars:
    docker_install_compose_plugin: true
    docker_install_compose: false
    docker_users:
      - "dean"
    rbenv_versions:
      - 3.2.2
      - 3.1.2
    rbenv_default_ruby: 3.2.2
    tailscale_up_skip: true

  roles:
    - update
    - common
    - geerlingguy.docker
    - artis3n.tailscale
    - users-dean
    - fish
    - { name: dotfiles, become: no }
    - { name: rbenv, become: no }
    - aws
    - flatpak
    - 1password
    - vscode
    - sublime
    - kopia

  tasks:
    - name: Remove Firefox-ESR
      ansible.builtin.apt:
        name: firefox-esr
        state: absent

    - name: Install database libraries
      ansible.builtin.apt:
        name:
          - sqlite3
          - libsqlite3-dev
          - default-mysql-client
          - default-libmysqlclient-dev
          - libpq-dev
        state: present
    - name: Install additional tools
      ansible.builtin.apt:
        name:
          - ffmpeg
          - libvips42
          - vlc
          - libavcodec-extra
        state: present
    
    - name: Create plugins directory
      file:
        state: directory
        path: '~/.var/app/org.mozilla.firefox/config/fontconfig'
      become: no

    - name: Fix Firefox Flatpak Fonts
      ansible.builtin.get_url:
        url: https://gist.githubusercontent.com/deanpcmad/396190f6bcf023d028ad8bb18debf30f/raw/fee14b1e38bf1c42dd8238100a5bf904299c81e5/fonts.conf 
        dest: "~/.var/app/org.mozilla.firefox/config/fontconfig/fonts.conf"
      become: no