---
- hosts: local
  become: true

  vars:
    docker_install_compose_plugin: true
    docker_install_compose: false
    docker_users:
      - "{{ user }}"

  roles:
    - update
    - common
    - geerlingguy.docker
