---
# allows {{ deb_architecture.stdout }} to be used to set the correct arch
- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Download Docker apt key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Update cache
  apt:
    update_cache: true

- name: Install Docker and Docker Compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - containerd.io
    state: present

- name: Add dean to docker group
  user:
    name: dean
    groups: docker
    append: yes