---
- name: Download Microsoft apt key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc 
    dest: /etc/apt/trusted.gpg.d/microsoft.asc

- name: Add VSCode repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: present

- name: Install VSCode
  ansible.builtin.apt:
    name: code 
    state: present
    update_cache: true
