---
- name: Download Microsoft signing key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/trusted.gpg.d/microsoft.asc

- name: Add VSCode repository
  ansible.builtin.apt_repository:
    repo:  "deb [signed-by=/etc/apt/trusted.gpg.d/microsoft.asc] https://packages.microsoft.com/repos/code stable main"
    name: vscode
    state: present
    update_cache: yes

- name: Install VSCode
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: true
