---
- name: Add VSCode repo with signing key
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: "https://packages.microsoft.com/repos/code"
    suites: [stable]
    components: [main]
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    enabled: yes

- name: Install VSCode
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: true
