---
- name: Install Atuin
  block:
    - name: Download Atuin install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ellie/atuin/main/install.sh
        dest: /tmp/atuin_install.sh
        mode: '0755'

    - name: Run Atuin install script
      ansible.builtin.shell: /tmp/atuin_install.sh
