---
- name: Add Kopia repo with signing key
  ansible.builtin.deb822_repository:
    name: kopia
    types: [deb]
    uris: "http://packages.kopia.io/apt"
    suites: [stable]
    components: [main]
    signed_by: https://kopia.io/signing-key
    state: present
    enabled: yes

- name: Install Kopia and Kopia UI
  ansible.builtin.apt:
    name:
      - kopia
      - kopia-ui
    state: present
    update_cache: true
