---
- name: Add Nextcloud repository
  ansible.builtin.apt_repository:
    repo: "ppa:nextcloud-devs/client"
    state: present

- name: Install Nextcloud
  ansible.builtin.apt:
    name: nextcloud-desktop
    state: present
    update_cache: true
