---
- name: Install development requirements
  ansible.builtin.apt:
    name:
      - build-essential
      - autoconf
      - patch
      - rustc
      - libyaml-dev
      - libreadline6-dev
      - libgmp-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev
      - libdb-dev
      - uuid-dev
      - zlib1g-dev
      - libssl-dev
      - gnupg
      - automake
    state: present
  become: yes

- name: Checkout asdf repo
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: '~/.asdf'
    accept_hostkey: yes

- name: Install ruby plugin
  shell: "~/.asdf/bin/asdf plugin add ruby"

- name: Install nodejs plugin
  shell: "~/.asdf/bin/asdf plugin add nodejs"

- name: Install Ruby 3.3.2
  shell: "~/.asdf/bin/asdf install ruby 3.3.2"

- name: Install Node.js 20.14.0
  shell: "~/.asdf/bin/asdf install nodejs 20.14.0"

- name: Set Ruby 3.3.2 as default
  shell: "~/.asdf/bin/asdf global ruby 3.3.2"

- name: Set Node.js 20.14.0 as default
  shell: "~/.asdf/bin/asdf global nodejs 20.14.0"
