---
- name: Install Flatpak
  ansible.builtin.apt:
    name: flatpak
    state: present

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install the Google Chrome flatpak
  community.general.flatpak:
    name: com.google.Chrome
    state: present

- name: Install the Nextcloud flatpak
  community.general.flatpak:
    name: com.nextcloud.desktopclient.nextcloud
    state: present

- name: Install the Spotify flatpak
  community.general.flatpak:
    name: com.spotify.Client
    state: present

- name: Install the Discord flatpak
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present

- name: Install the Obsidian flatpak
  community.general.flatpak:
    name: md.obsidian.Obsidian
    state: present

- name: Install the Cryptomator flatpak
  community.general.flatpak:
    name: org.cryptomator.Cryptomator
    state: present

- name: Install the DBeaver flatpak
  community.general.flatpak:
    name: io.dbeaver.DBeaverCommunity
    state: present

- name: Install the Steam flatpak
  community.general.flatpak:
    name: com.valvesoftware.Steam
    state: present

- name: Install the Flatseal flatpak
  community.general.flatpak:
    name: com.github.tchx84.Flatseal
    state: present
