---
- name: Download AWS CLI v2
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip
    dest: /tmp/awscliv2.zip

- name: Extract awscliv2.zip into /tmp
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes

- name: Install AWS CLI v2
  shell: "/tmp/aws/install"
  args:
    creates: "/usr/local/bin/aws"
  become: yes
