---
- name: Download Sublime Text apt key
  ansible.builtin.get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg 
    dest: /etc/apt/trusted.gpg.d/sublime-text.asc

- name: Add Sublime Text repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
    filename: sublime-text
    state: present

- name: Install Sublime Text and Sublime Merge
  ansible.builtin.apt:
    name:
      - sublime-text
      - sublime-merge
    state: present
    update_cache: true
