---
- name: Add SublimeHQ repo with signing key
  ansible.builtin.deb822_repository:
    name: sublime
    types: [deb]
    uris: "https://download.sublimetext.com"
    suites: ["apt/stable/"]
    signed_by: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
    enabled: yes

- name: Install Sublime Merge
  ansible.builtin.apt:
    name: sublime-merge
    state: present
    update_cache: true
