---
- name: Install common tools
  ansible.builtin.apt:
    name:
      - htop
      - btop
      - wget
      - curl
      - nano
      - unzip
      - git
      - software-properties-common
      - apt-transport-https
      # Fingerprint
      - fprintd
      - libpam-fprintd
    state: present
