---
- name: Add Debian Unstable repository
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian/ unstable main contrib non-free"
    filename: debian-unstable
    state: present

- name: Add apt pin
  copy: src=./roles/debian-unstable/files/99unstable dest=/etc/apt/preferences.d/99unstable

- name: Install Firefox and Thunderbird from unstable repo
  ansible.builtin.apt:
    name:
      - firefox
      - thunderbird
    default_release: unstable
    state: present