---
- name: Install development requirements
  ansible.builtin.apt:
    name:
      - build-essential
      - autoconf
      - patch
      - rustc
      - libyaml-dev
      - libreadline6-dev
      - libgmp-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev
      - libdb-dev
      - uuid-dev
      - zlib1g-dev
      - libssl-dev
      - gnupg
      - automake
    state: present
  become: yes

- name: Checkout rbenv repo to '{{ rbenv_root }}'
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: '{{ rbenv_root }}'
    accept_hostkey: yes

- name: Create plugins directory
  file:
    state: directory
    path: '{{ rbenv_root }}/plugins'

- name: Checkout ruby-build plugin repo to '{{ rbenv_root }}/plugins'
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: '{{ rbenv_root }}/plugins/ruby-build'
    accept_hostkey: yes

- name: Checkout rbenv-default-gems plugin repo to '{{ rbenv_root }}/plugins'
  git:
    repo: https://github.com/rbenv/rbenv-default-gems.git
    dest: '{{ rbenv_root }}/plugins/rbenv-default-gems'
    accept_hostkey: yes

- name: Set default-gems
  copy:
    src: default-gems
    dest: '~/.default-gems'

- name: Install specified Ruby versions
  shell: "~/.rbenv/bin/rbenv install {{ item }}"
  args:
    creates: "~/.rbenv/versions/{{ item }}"
  loop: "{{ rbenv_versions }}"
  loop_control:
    label: "Install Ruby {{ item }}"

- name: Create symbolic link of lib to lib64
  file:
    src: "~/.rbenv/versions/{{ item }}/openssl/lib64"
    dest: "~/.rbenv/versions/{{ item }}/openssl/lib"
    state: link
  loop: "{{ rbenv_versions }}"

- name: Set Ruby {{ rbenv_default_ruby }} as default
  shell: "{{ rbenv_root }}/bin/rbenv global {{ rbenv_default_ruby }} && {{ rbenv_root }}/bin/rbenv rehash"
