---
- name: Download 1Password apt key
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/keys/1password.asc
    dest: /etc/apt/keyrings/1password.asc
    mode: '0644'

- name: Add 1Password repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/1password.asc] https://downloads.1password.com/linux/debian/amd64 stable main"
    filename: 1password
    state: present

- name: Install 1Password and 1Password CLI
  ansible.builtin.apt:
    name:
      - 1password
      - 1password-cli
    state: present
    update_cache: true
